name: Fake release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of simulated release'
        required: true
        type: string
      key:
        description: 'Key for version file update'
        required: false
        type: string
        default: 'homeassistant[]'
      channel:
        description: 'Channel'
        required: false
        type: string
        default: 'dev'
      rollout:
        description: 'Generate rollout plan for staged rollouts'
        required: false
        type: boolean
        default: false
 
  release:
    types: ["published"]

jobs:
  init:
    name: Init release
    runs-on: ubuntu-22.04
    outputs:
      channel: ${{ steps.channel.outputs.channel }}
    steps:
      - name: Get channel
        id: channel
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
              echo "channel=beta" >> "$GITHUB_OUTPUT"
            else
              echo "channel=stable" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "channel=${{ inputs.channel }}" >> "$GITHUB_OUTPUT"
          fi

  publish_ha:
    name: Publish version files
    environment: ${{ needs.init.outputs.channel }}
    needs: ["init"]
    runs-on: ubuntu-latest
    steps:
    - name: Initialize git
      uses: home-assistant/actions/helpers/git-init@master
      with:
        name: ${{ secrets.GIT_NAME }}
        email: ${{ secrets.GIT_EMAIL }}
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update version file
      uses: agners/home-assistant-actions/helpers/version-push@master
      with:
        key: ${{ inputs.key }}
        key-description: "Home Assistant ${{ inputs.key }}"
        version: ${{ inputs.version }}
        channel: ${{ needs.init.outputs.channel }}
        rollout: ${{ inputs.rollout }}

    - name: Update version file (beta -> stable PR)
      if: needs.init.outputs.channel == 'beta'
      uses: agners/home-assistant-actions/helpers/version-push@master
      with:
        key: ${{ inputs.key }}
        key-description: "Home Assistant ${{ inputs.key }}"
        version: ${{ inputs.version }}
        channel: stable
        rollout: ${{ inputs.rollout }}
        create-pr: 'true'

    - name: Update version file (stable -> beta)
      if: needs.init.outputs.channel == 'stable'
      uses: agners/home-assistant-actions/helpers/version-push@master
      with:
        key: ${{ inputs.key }}
        key-description: "Home Assistant ${{ inputs.key }}"
        version: ${{ inputs.version }}
        channel: beta

